### ISSUE TITLE
Support for sidekiq >= 4

### ISSUE THREAD

**Issue by rngtng** [queue-bus/sidekiq-bus#5]
Hey. Thanks for this great gem! We'd only like to use it with sidekiq >= 4. What are the blocker for upgrading this to latest version?

**Comment by bleonard** [comment]
is the api different for sidekiq 4?

**Comment by rngtng** [comment]
Nothing of what i'm aware of...

The gemspec is very restrictive with the version so I wondered why..?

**Comment by bleonard** [comment]
There's no reason that I know of other than it not being tested in code or production. Interested in trying?

**Comment by rngtng** [comment]
done: https://github.com/queue-bus/sidekiq-bus/pull/7
